name: github

on:
  pull_request_target:
    types: [opened, reopened]
  issues:
    types:
      - labeled

permissions:
  pull-requests: write
  pull-requests: read
  issues: write
  issues: read

jobs:
  pr-assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v1.4.0
  issue-assign-author:
    if: github.event.label.name != 'bug'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: toshimaru/auto-author-assign@v1.4.0